import 'package:drift/drift.dart';

// =============================================================================
// SYSTEM TABLES
// =============================================================================

@DataClassName('MusicFolder')
class Folders extends Table {
  /// The absolute path to the directory (e.g., /storage/emulated/0/Music)
  TextColumn get path => text().unique()();
  
  IntColumn get lastScanned => integer().withDefault(const Constant(0))();
  BoolColumn get isEnabled => boolean().withDefault(const Constant(true))();
}

// =============================================================================
// MUSIC METADATA TABLES
// =============================================================================

@DataClassName('ArtistEntity')
class Artists extends Table {
  IntColumn get id => integer().autoIncrement()();
  
  /// Normalized artist name. Unique to prevent duplicates like "Drake" vs "drake".
  TextColumn get name => text().unique()();
}

@DataClassName('AlbumEntity')
class Albums extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  
  /// The "Album Artist" (e.g., "Various Artists" for compilations).
  IntColumn get artistId => integer().references(Artists, #id)();
  
  IntColumn get year => integer().withDefault(const Constant(0))();
  
  /// Path to the cached album art image (generated by the scanner).
  TextColumn get artPath => text().nullable()();
}

@DataClassName('SongEntity')
class Songs extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  
  // Metadata
  IntColumn get trackNumber => integer().withDefault(const Constant(0))();
  IntColumn get discNumber => integer().withDefault(const Constant(0))();
  IntColumn get duration => integer().withDefault(const Constant(0))();
  
  // File Info
  TextColumn get path => text().unique()();
  IntColumn get lastModified => integer().withDefault(const Constant(0))();

  // Relationships
  /// The "Primary" artist. Used for sorting A-Z and main list display.
  IntColumn get artistId => integer().references(Artists, #id)();
  IntColumn get albumId => integer().references(Albums, #id)();
}

// =============================================================================
// JUNCTION TABLES (Relationships)
// =============================================================================

/// Links a Song to potentially multiple Artists.
/// Used for "Featuring" artists or collaborations.
@DataClassName('SongArtistEntity')
class SongArtists extends Table {
  // onDelete: KeyAction.cascade -> If the Song is deleted, this link is auto-removed.
  IntColumn get songId => integer().references(Songs, #id, onDelete: KeyAction.cascade)();
  IntColumn get artistId => integer().references(Artists, #id, onDelete: KeyAction.cascade)();
  
  @override
  Set<Column> get primaryKey => {songId, artistId};
}