name: nordplayer
description: "A simple, modern music player."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  path_provider: ^2.1.5
  path: ^1.9.1
  file_selector: ^1.1.0
  logger: ^2.6.2
  shared_preferences: ^2.5.4
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  metadata_god: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/
