name: nordplayer
description: "A simple, modern music player."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  path: ^1.9.1
  watcher: ^1.2.1

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_selector: ^1.1.0
  go_router: ^17.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4

  # Third parties
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  flutter_riverpod: ^3.2.1
  logger: ^2.6.2
  media_kit: ^1.2.6
  media_kit_libs_audio: ^1.0.7
  metadata_god: ^1.1.0
  riverpod_lint: ^3.1.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.11.1

  # Third parties
  drift_dev: ^2.31.0

flutter:
  uses-material-design: true

  assets:
    - assets/
